# Generated by Django 3.1.5 on 2021-01-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210131_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
