# Generated by Django 3.1.5 on 2021-01-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
